# Core configurable options for LWC
core:

    # The language LWC will use, specified by the shortname. For example, English = en, French = fr, German = de,
    # and so on
    locale: en

    # How often updates are batched to the database (in seconds). If set to a higher value than 10, you may have
    # some unexpected results, especially if your server is prone to crashing.
    flushInterval: 10

    # LWC regularly caches protections locally to prevent the database from being queried as often. The default is 10000
    # and for most servers is OK. LWC will also fill up to <precache> when the server is started automatically.
    cacheSize: 10000

    # How many protections are precached on startup. If set to -1, it will use the cacheSize value instead and precache
    # as much as possible
    precache: -1

    # If true, players will be sent a notice in their chat box when they open a protection they have access to, but
    # not their own unless <showMyNotices> is set to true
    showNotices: true

    # If true, players will be sent a notice in their chat box when they open a protection they own.
    showMyNotices: false

    # If true, ops will be considered LWC admins (e.g with a Permissions plugin, considered to have lwc.admin) and thus
    # will have very destructive LWC commands.
    opIsLWCAdmin: true

    # If true, LWC will not log history about protections. If you are using LWC-Economy and this is disabled, you will
    # NOT receive refunds for purchased protections
    disableHistory: true

    # if true, LWC will only allow members of a faction to register protections in claims via the Factions plugin
    factionCheck: false

    # The permission node prefix that is used to match player groups when
    # no supported permission plugin is found, e.g group.vip matches the player's group as vip
    groupPrefix: 'group.'

    # If you will be notified of LWC updates
    updateNotifier: true

# "Fun" options
optional:

    # Protections are only active when a player is online.
    # So if a player is offline, anyone can access it. If the player is online, it functions normally
    onlyProtectWhenOwnerIsOnline: false

    # Protections are only active when a player is offline
    onlyProtectWhenOwnerIsOffline: false

    # Block IDs to automatically blocks from /lwc admin purge, /lwc admin expire, etc.
    exemptBlocks: []

    # Opt out of the optional metrics tooling
    # Available online: http://metrics.griefcraft.com/plugin/LWC/
    optOut: false

    # Blocks that cannot be placed around someone else's protection. This is most useful
    blacklistedBlocks:
    - 166

    # Players that are blocked from destroying any blocks protected by LWC. Mainly useful for MCPC
    # where mods can remove blocks and try to break the block by sending an event first (e.g turtle)
    blacklistedPlayers:
    - player

    # If protections limits will be enabled (defaults to unlimited protections)
    useProtectionLimits: true

    # If true, LWC will show certain (not all) messages in the action bar instead of the chat.
    # Spigot or better is recommended. This option will have no effect on CraftBukkit servers.
    useActionBar: false
    
    # This disables protection checks for any item moves except for hopper minecarts. Protection against
    # hoppers is now done by checking for protections of the containers that the hopper is pointing into
    # or that are above the hopper when the player places a hopper. If the player doesn't have access to
    # that protection or the hopper flag isn't allowing it then the placement is blocked.
    alternativeHopperProtection: false

    # If true, LWC will format protection information for better readability. Otherwise, raw protection
    # information will be displayed instead (default in versions prior to 2.2.3).
    useFormattedInfo: true
    
# Database information for LWC
database:

    # The database adapter to use, for example sqlite (default) or mysql
    adapter: sqlite

    # This is strictly for SQLite only and should be left alone. When changing to MySQL and this is left intact,
    # LWC will automatically convert your protections from SQLite to MySQL
    path: 'plugins/LWC/lwc.db'

    # The MySQL host. You can specify a non-default port (3306) by adding :port, e.g host: 'localhost:3307'
    host: 'localhost'

    # The database LWC should use to store data (not necessary for SQLite)
    database: 'lwc'

    # The username LWC should use to connect to the server with (not necessary for SQLite)
    username: ''

    # The password LWC should use to connect to the server with (not necessary for SQLite)
    password: ''

    # The prefix for LWC tables. For example, a prefix of 'lwc_' will make
    # the protections table show up as lwc_protections
    prefix: 'lwc_'

    # The interval between pinging the MySQL server to keep it alive (in seconds)
    ping_interval: 300

# The protections nodes allows you to define, remove and modify which blocks LWC is allowed to protect
# This means that you could make any block you want protectable, or remove existing protectable blocks
# (e.g trap doors, etc.)
protections:
    # These values serve as default values for the protections defined under blocks

    # If true, the default behaviour will be to BLOCK redstone to protections, and /credstone on (Protection Flag)
    # will ALLOW redstone to the protection
    # If false, the default behaviour will be to ALLOW redstone to protections, and /credstone on will
    # BLOCK redstone to the protection
    denyRedstone: false

    # If true, hoppers will by blocked by DEFAULT and /chopper on will enable hopper use on them
    # If false, hoppers will be enabled by DEFAULT and /chopper on will disable hopper use on them
    denyHoppers: true

    # Settable to private, public, donation, or off. It defines what protections are registered as when you place them
    # on the ground
    autoRegister: off

    # Used in very specific use-cases: makes LWC ignore block destruction for the given block or all blocks, allowing
    # players to remove the block and resulting protection.
    ignoreBlockDestruction: false

    # If left clicking should be ignored by LWC. An example of this would be to add ignoreLeftClick under a note block
    # protection to allow players to play the note block's note, but not change the note (which is done via right click,
    # which would be blocked by LWC.)
    ignoreLeftClick: false

    # If right clicking should be ignored by LWC.
    ignoreRightClick: false

    # If LWC should ignore explosions to the protection. For example, you could allow Doors to be blown by explosions,
    # but not chests.
    ignoreExplosions: false

    # If entities - such as zombies - are allowed to break down doors
    allowEntityBreakDoor: false

    # If entities - such as villagers - should be allowed to interact with protections (i.e doors)
    allowEntityInteract: false

    # Creation messages and protection notices will not be shown for this protection
    quiet: false

    # Set to true to prevent users from modifying a protection they own of a certain type (or any protection).
    # ONLY lwc admins will be able to modify the protection
    readonly-modify: false

    # Set to true to prevent users from removing a protection they own of a certain type (or any protection).
    # ONLY lwc admins will be able to modify the protection
    readonly-remove: false

    # Current and custom protections are defined here by their block name or id
    # If you use the Id, you MUST encase it in quotes, for example (chest):
    # '54':
    #     enabled: true
    # The custom protection must also have enabled: true under it for it to function in the world
    blocks:
        chest:
            enabled: true
            autoRegister: private
        trapped_chest:
            enabled: true
            autoRegister: private
        furnace:
            enabled: true
            autoRegister: private
        blast_furnace:
            enabled: true
            autoRegister: private
        smoker:
            enabled: true
            autoRegister: private
        dispenser:
            enabled: true
            autoRegister: private
        dropper:
            enabled: true
            autoRegister: private
        barrel:
            enabled: true
            autoRegister: private
        composter:
            enabled: true
            autoRegister: private
        lectern:
            enabled: true
            autoRegister: private
        shulker_box:
            enabled: true
            autoRegister: private
        white_shulker_box:
            enabled: true
            autoRegister: private
        orange_shulker_box:
            enabled: true
            autoRegister: private
        magenta_shulker_box:
            enabled: true
            autoRegister: private
        light_blue_shulker_box:
            enabled: true
            autoRegister: private
        yellow_shulker_box:
            enabled: true
            autoRegister: private
        lime_shulker_box:
            enabled: true
            autoRegister: private
        pink_shulker_box:
            enabled: true
            autoRegister: private
        gray_shulker_box:
            enabled: true
            autoRegister: private
        light_gray_shulker_box:
            enabled: true
            autoRegister: private
        cyan_shulker_box:
            enabled: true
            autoRegister: private
        purple_shulker_box:
            enabled: true
            autoRegister: private
        blue_shulker_box:
            enabled: true
            autoRegister: private
        brown_shulker_box:
            enabled: true
            autoRegister: private
        green_shulker_box:
            enabled: true
            autoRegister: private
        red_shulker_box:
            enabled: true
            autoRegister: private
        black_shulker_box:
            enabled: true
            autoRegister: private
        sign:
            enabled: true
        iron_door:
            enabled: true
        oak_door:
            enabled: true
        spruce_door:
            enabled: true
        birch_door:
            enabled: true
        jungle_door:
            enabled: true
        acacia_door:
            enabled: true
        dark_oak_door:
            enabled: true
        mangrove_door:
            enabled: true
        crimson_door:
            enabled: true
        warped_door:
            enabled: true
        iron_trapdoor:
            enabled: true
        oak_trapdoor:
            enabled: true
        spruce_trapdoor:
            enabled: true
        birch_trapdoor:
            enabled: true
        jungle_trapdoor:
            enabled: true
        acacia_trapdoor:
            enabled: true
        dark_oak_trapdoor:
            enabled: true
        mangrove_trapdoor:
            enabled: true
        crimson_trapdoor:
            enabled: true
        warped_trapdoor:
            enabled: true
        oak_fence_gate:
            enabled: true
        spruce_fence_gate:
            enabled: true
        birch_fence_gate:
            enabled: true
        jungle_fence_gate:
            enabled: true
        acacia_fence_gate:
            enabled: true
        dark_oak_fence_gate:
            enabled: true
        mangrove_fence_gate:
            enabled: true
        crimson_fence_gate:
            enabled: true
        warped_fence_gate:
            enabled: true
        white_banner:
            enabled: true
        orange_banner:
            enabled: true
        magenta_banner:
            enabled: true
        light_blue_banner:
            enabled: true
        yellow_banner:
            enabled: true
        lime_banner:
            enabled: true
        pink_banner:
            enabled: true
        gray_banner:
            enabled: true
        light_gray_banner:
            enabled: true
        cyan_banner:
            enabled: true
        purple_banner:
            enabled: true
        blue_banner:
            enabled: true
        brown_banner:
            enabled: true
        green_banner:
            enabled: true
        red_banner:
            enabled: true
        black_banner:
            enabled: true
        white_wall_banner:
            enabled: true
        orange_wall_banner:
            enabled: true
        magenta_wall_banner:
            enabled: true
        light_blue_wall_banner:
            enabled: true
        yellow_wall_banner:
            enabled: true
        lime_wall_banner:
            enabled: true
        pink_wall_banner:
            enabled: true
        gray_wall_banner:
            enabled: true
        light_gray_wall_banner:
            enabled: true
        cyan_wall_banner:
            enabled: true
        purple_wall_banner:
            enabled: true
        blue_wall_banner:
            enabled: true
        brown_wall_banner:
            enabled: true
        green_wall_banner:
            enabled: true
        red_wall_banner:
            enabled: true
        black_wall_banner:
            enabled: true

modes:
    droptransfer:
        enabled: true

        # allow items to be transferred across world boundaries
        crossWorld: false
    persist:
        enabled: true
